apiVersion: kustomize.config.k8s.io/v1beta1

kind: Kustomization

images:
- name: 058264288247.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 058264288247.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 83e7d025

resources:
- ../../base

patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
- back-deployment-patch.yaml
- back-service-patch.yaml
